(function(){
'use strict';
const el=id=>document.getElementById(id);
function loadJSZip(){if(window.JSZip)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='/vendor_jszip.min.js';s.onload=ok;s.onerror=()=>no(new Error('未能載入 ZIP 工具'));document.head.appendChild(s)})}
function safeName(s){return String(s||'member').replace(/[\\/:*?"<>|]/g,'_')}
function canvasBlob(canvas){return new Promise(ok=>canvas.toBlob(ok,'image/png'))}
function latestMembers(){if(typeof data==='undefined'||!Array.isArray(data.batches)||!Array.isArray(data.members)||!data.batches.length)return[];const latest=[...data.batches].sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)))[0];return data.members.filter(m=>m.batch_id===latest.id)}
function ensureButton(){if(typeof role==='undefined'||role!=='admin'||el('downloadAllCardsV2'))return;const admin=el('adminView');if(!admin)return;const card=[...admin.querySelectorAll('.card')].find(x=>x.querySelector('#batchHistory'))||admin.querySelector('.card');if(!card)return;const b=document.createElement('button');b.id='downloadAllCardsV2';b.type='button';b.className='btn light';b.style.marginTop='12px';b.textContent='下載最新月份全部會員圖卡 ZIP';card.appendChild(b);b.onclick=downloadAll}
async function downloadAll(){const b=el('downloadAllCardsV2'),members=latestMembers();if(!members.length){alert('未有可下載嘅最新月份會員資料。');return}if(typeof window.drawMemberCardV2!=='function'){alert('會員圖卡工具尚未載入，請重新整理。');return}b.disabled=true;b.textContent=`正在製作 0／${members.length}`;try{await loadJSZip();const zip=new JSZip(),folder=zip.folder('member-cards');for(let i=0;i<members.length;i++){const m=members[i];if(typeof makeTips==='function')m.improvement_tips=makeTips(m);if(typeof makeRecap==='function')m.recap_text=makeRecap(m);const c=document.createElement('canvas');window.drawMemberCardV2(m,c);folder.file(`${safeName(m.member_name)}-traffic-light.png`,await canvasBlob(c));b.textContent=`正在製作 ${i+1}／${members.length}`}const blob=await zip.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='BNI-BINGO-latest-member-cards.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}catch(e){alert(e.message||'下載失敗')}finally{b.disabled=false;b.textContent='下載最新月份全部會員圖卡 ZIP'}}
function install(){ensureButton()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,500);document.addEventListener('click',e=>{if(e.target?.id==='adminTab')setTimeout(install,0)});
})();