(function(){
'use strict';
const el=id=>document.getElementById(id);
function safeName(s){return String(s||'member').replace(/[\\/:*?"<>|]/g,'_')}
function canvasBlob(canvas){return new Promise((ok,no)=>canvas.toBlob(blob=>blob?ok(blob):no(new Error('未能產生會員圖卡')),'image/png'))}
function pause(){return new Promise(ok=>setTimeout(ok,0))}
function latestReport(){if(typeof data==='undefined'||!Array.isArray(data.batches)||!Array.isArray(data.members)||!data.batches.length)return{batch:null,members:[]};const batch=[...data.batches].sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)))[0];return{batch,members:data.members.filter(m=>m.batch_id===batch.id)}}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function dosStamp(d=new Date()){const year=Math.max(1980,d.getFullYear()),date=((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate(),time=(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1);return{date,time}}
function view(size){const a=new Uint8Array(size);return{a,d:new DataView(a.buffer)}}
function concat(parts){const total=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(total);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length}return out}
function buildZip(files){const enc=new TextEncoder(),locals=[],centrals=[],stamp=dosStamp();let offset=0;for(const file of files){const name=enc.encode(file.name),bytes=file.data instanceof Uint8Array?file.data:new Uint8Array(file.data),crc=crc32(bytes),size=bytes.length;const local=view(30);let d=local.d;d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x0800,true);d.setUint16(8,0,true);d.setUint16(10,stamp.time,true);d.setUint16(12,stamp.date,true);d.setUint32(14,crc,true);d.setUint32(18,size,true);d.setUint32(22,size,true);d.setUint16(26,name.length,true);d.setUint16(28,0,true);locals.push(local.a,name,bytes);const central=view(46);d=central.d;d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x0800,true);d.setUint16(10,0,true);d.setUint16(12,stamp.time,true);d.setUint16(14,stamp.date,true);d.setUint32(16,crc,true);d.setUint32(20,size,true);d.setUint32(24,size,true);d.setUint16(28,name.length,true);d.setUint16(30,0,true);d.setUint16(32,0,true);d.setUint16(34,0,true);d.setUint16(36,0,true);d.setUint32(38,0,true);d.setUint32(42,offset,true);centrals.push(central.a,name);offset+=30+name.length+size}const centralDirectory=concat(centrals),end=view(22),d=end.d;d.setUint32(0,0x06054b50,true);d.setUint16(4,0,true);d.setUint16(6,0,true);d.setUint16(8,files.length,true);d.setUint16(10,files.length,true);d.setUint32(12,centralDirectory.length,true);d.setUint32(16,offset,true);d.setUint16(20,0,true);return concat([...locals,centralDirectory,end.a])}
function ensureButton(){if(typeof role==='undefined'||role!=='admin'||el('downloadAllCardsV2'))return;const admin=el('adminView');if(!admin)return;const card=[...admin.querySelectorAll('.card')].find(x=>x.querySelector('#batchHistory'))||admin.querySelector('.card');if(!card)return;const b=document.createElement('button');b.id='downloadAllCardsV2';b.type='button';b.className='btn light';b.style.marginTop='12px';b.textContent='下載最新月份全部會員圖卡 ZIP';card.appendChild(b);b.onclick=downloadAll}
async function downloadAll(){const b=el('downloadAllCardsV2'),{batch,members}=latestReport();if(!members.length){alert('未有可下載嘅最新月份會員資料。');return}if(typeof window.drawMemberCardV2!=='function'){alert('會員圖卡工具尚未載入，請重新整理。');return}b.disabled=true;b.textContent=`正在製作 0／${members.length}`;const files=[],canvas=document.createElement('canvas');try{for(let i=0;i<members.length;i++){const m=members[i];if(typeof makeTips==='function')m.improvement_tips=makeTips(m);if(typeof makeRecap==='function')m.recap_text=makeRecap(m);window.drawMemberCardV2(m,canvas);const blob=await canvasBlob(canvas),bytes=new Uint8Array(await blob.arrayBuffer());files.push({name:`member-cards/${safeName(m.member_name)}-traffic-light.png`,data:bytes});b.textContent=`正在製作 ${i+1}／${members.length}`;if((i+1)%3===0)await pause()}b.textContent='正在整理 ZIP…';const zipBytes=buildZip(files),url=URL.createObjectURL(new Blob([zipBytes],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download=`BNI-BINGO-${batch?.period_end?.slice(0,7)||'latest'}-member-cards.zip`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){console.error('Bulk card ZIP failed',e);alert(e?.message||'下載失敗，請重新整理後再試。')}finally{canvas.width=1;canvas.height=1;b.disabled=false;b.textContent='下載最新月份全部會員圖卡 ZIP'}}
function install(){ensureButton()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,500);document.addEventListener('click',e=>{if(e.target?.id==='adminTab')setTimeout(install,0)});
})();