(function(){
'use strict';
const el=id=>document.getElementById(id);
const scopes={
  non_green:{label:'黃燈或以下（需要改善）',button:'下載黃燈或以下圖卡 ZIP',slug:'yellow-or-below',match:m=>lightOf(m)!=='green'},
  all:{label:'全部會員',button:'下載全部會員圖卡 ZIP',slug:'all',match:()=>true},
  yellow:{label:'只下載黃燈',button:'下載黃燈會員圖卡 ZIP',slug:'yellow',match:m=>lightOf(m)==='yellow'},
  red_black:{label:'紅燈及黑燈',button:'下載紅燈及黑燈圖卡 ZIP',slug:'red-black',match:m=>['red','black'].includes(lightOf(m))}
};
function safeName(s){return String(s||'member').replace(/[\\/:*?"<>|]/g,'_')}
function canvasBlob(canvas){return new Promise((ok,no)=>canvas.toBlob(blob=>blob?ok(blob):no(new Error('未能產生會員圖卡')),'image/png'))}
function pause(){return new Promise(ok=>setTimeout(ok,0))}
function lightOf(m){const value=String(m?.light||'').toLowerCase();if(['green','yellow','red','black'].includes(value))return value;const score=Number(m?.total_score)||0;return score>=70?'green':score>=50?'yellow':score>=30?'red':'black'}
function latestReport(){if(typeof data==='undefined'||!Array.isArray(data.batches)||!Array.isArray(data.members)||!data.batches.length)return{batch:null,members:[]};const batch=[...data.batches].sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)))[0];return{batch,members:data.members.filter(m=>m.batch_id===batch.id)}}
function selectedScope(){return scopes[el('bulkCardScopeV2')?.value]||scopes.non_green}
function selectedMembers(){const report=latestReport(),scope=selectedScope();return{...report,scope,members:report.members.filter(scope.match)}}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function dosStamp(d=new Date()){const year=Math.max(1980,d.getFullYear()),date=((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate(),time=(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1);return{date,time}}
function view(size){const a=new Uint8Array(size);return{a,d:new DataView(a.buffer)}}
function concat(parts){const total=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(total);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length}return out}
function buildZip(files){const enc=new TextEncoder(),locals=[],centrals=[],stamp=dosStamp();let offset=0;for(const file of files){const name=enc.encode(file.name),bytes=file.data instanceof Uint8Array?file.data:new Uint8Array(file.data),crc=crc32(bytes),size=bytes.length;const local=view(30);let d=local.d;d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x0800,true);d.setUint16(8,0,true);d.setUint16(10,stamp.time,true);d.setUint16(12,stamp.date,true);d.setUint32(14,crc,true);d.setUint32(18,size,true);d.setUint32(22,size,true);d.setUint16(26,name.length,true);d.setUint16(28,0,true);locals.push(local.a,name,bytes);const central=view(46);d=central.d;d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x0800,true);d.setUint16(10,0,true);d.setUint16(12,stamp.time,true);d.setUint16(14,stamp.date,true);d.setUint32(16,crc,true);d.setUint32(20,size,true);d.setUint32(24,size,true);d.setUint16(28,name.length,true);d.setUint16(30,0,true);d.setUint16(32,0,true);d.setUint16(34,0,true);d.setUint16(36,0,true);d.setUint32(38,0,true);d.setUint32(42,offset,true);centrals.push(central.a,name);offset+=30+name.length+size}const centralDirectory=concat(centrals),end=view(22),d=end.d;d.setUint32(0,0x06054b50,true);d.setUint16(4,0,true);d.setUint16(6,0,true);d.setUint16(8,files.length,true);d.setUint16(10,files.length,true);d.setUint32(12,centralDirectory.length,true);d.setUint32(16,offset,true);d.setUint16(20,0,true);return concat([...locals,centralDirectory,end.a])}
function refreshControls(){const b=el('downloadAllCardsV2'),note=el('bulkCardCountV2');if(!b)return;const {members,scope}=selectedMembers(),all=latestReport().members;b.textContent=`${scope.button}（${members.length}位）`;b.disabled=!members.length;if(note)note.textContent=`最新月份共 ${all.length} 位會員；目前範圍會下載 ${members.length} 位。綠燈會員預設不包括在改善圖內。`}
function ensureControls(){if(typeof role==='undefined'||role!=='admin')return;const admin=el('adminView');if(!admin)return;const card=[...admin.querySelectorAll('.card')].find(x=>x.querySelector('#batchHistory'))||admin.querySelector('.card');if(!card)return;let tools=el('bulkCardToolsV2');if(!tools){tools=document.createElement('div');tools.id='bulkCardToolsV2';tools.className='bulk-card-tools-v2';tools.innerHTML=`<div class="bulk-card-filter-v2"><label for="bulkCardScopeV2"><strong>改善圖下載範圍</strong></label><select id="bulkCardScopeV2" class="field"><option value="non_green">黃燈或以下（需要改善）</option><option value="all">全部會員</option><option value="yellow">只下載黃燈</option><option value="red_black">紅燈及黑燈</option></select><small id="bulkCardCountV2" class="muted"></small></div><button id="downloadAllCardsV2" type="button" class="btn light">下載黃燈或以下圖卡 ZIP</button>`;card.appendChild(tools);el('bulkCardScopeV2').onchange=refreshControls;el('downloadAllCardsV2').onclick=downloadAll}refreshControls()}
async function downloadAll(){const b=el('downloadAllCardsV2'),{batch,members,scope}=selectedMembers();if(!members.length){alert(`最新月份未有符合「${scope.label}」條件嘅會員。`);refreshControls();return}if(typeof window.drawMemberCardV2!=='function'){alert('會員圖卡工具尚未載入，請重新整理。');return}b.disabled=true;b.textContent=`正在製作 0／${members.length}`;const files=[],canvas=document.createElement('canvas');try{for(let i=0;i<members.length;i++){const m=members[i];if(typeof makeTips==='function')m.improvement_tips=makeTips(m);if(typeof makeRecap==='function')m.recap_text=makeRecap(m);window.drawMemberCardV2(m,canvas);const blob=await canvasBlob(canvas),bytes=new Uint8Array(await blob.arrayBuffer());files.push({name:`member-cards/${safeName(m.member_name)}-traffic-light.png`,data:bytes});b.textContent=`正在製作 ${i+1}／${members.length}`;if((i+1)%3===0)await pause()}b.textContent='正在整理 ZIP…';const zipBytes=buildZip(files),url=URL.createObjectURL(new Blob([zipBytes],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download=`BNI-BINGO-${batch?.period_end?.slice(0,7)||'latest'}-${scope.slug}-member-cards.zip`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){console.error('Bulk card ZIP failed',e);alert(e?.message||'下載失敗，請重新整理後再試。')}finally{canvas.width=1;canvas.height=1;b.disabled=false;refreshControls()}}
function install(){ensureControls()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,500);document.addEventListener('click',e=>{if(e.target?.id==='adminTab')setTimeout(install,0)});const oldRenderAll=window.renderAll;if(typeof oldRenderAll==='function'&&!oldRenderAll.__bulkScopeWrapped){const wrapped=function(){const out=oldRenderAll.apply(this,arguments);setTimeout(refreshControls,0);return out};wrapped.__bulkScopeWrapped=true;window.renderAll=wrapped}
})();