(function(){
'use strict';
const el=id=>document.getElementById(id);
let report=null,sourceBase64=null,mode='latest';
const norm=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase();
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const light=(v,s)=>{v=String(v).toLowerCase();if(v.includes('綠')||v.includes('green'))return'green';if(v.includes('黃')||v.includes('yellow'))return'yellow';if(v.includes('紅')||v.includes('red'))return'red';if(v.includes('黑')||v.includes('black'))return'black';return s>=70?'green':s>=50?'yellow':s>=30?'red':'black'};
const lightName=l=>({green:'綠燈',yellow:'黃燈',red:'紅燈',black:'黑燈'})[l]||l;
const num=v=>Number(String(v??0).replace(/[$,HKD\s]/gi,''))||0;
function file64(f){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)})}
function monthEnd(y,m){return new Date(Date.UTC(+y,+m,0)).getUTCDate()}
function detectPeriod(filename){let d=filename.match(/(20\d{2})[-_ ]?(\d{1,2})/);if(!d){d=filename.match(/(?:^|\D)(\d{1,2})[-_ ]?(20\d{2})(?:\D|$)/);if(d)d=[d[0],d[2],d[1]]}if(!d)return null;const y=d[1],m=String(d[2]).padStart(2,'0'),day=String(monthEnd(y,m)).padStart(2,'0');return{start:`${y}-${m}-01`,end:`${y}-${m}-${day}`}}
function scoreSum(m){return ['training_score','absence_score','lateness_score','one_to_one_score','referral_score','biz_give_score','visitor_score'].reduce((s,k)=>s+num(m[k]),0)}
function ensureUI(){const card=el('file')?.closest('.card');if(!card)return;let modeBox=el('publishMode');if(!modeBox){modeBox=document.createElement('div');modeBox.id='publishMode';modeBox.className='mode-box hide';el('checkResult').after(modeBox)}let row=card.querySelector('.row');if(!row){row=document.createElement('div');row.className='row';card.appendChild(row)}const buttons=[['publishBtn','確認發布','btn'],['resetBtn','取消上載','btn light'],['downloadCsvBtn','下載核對 CSV','btn light']];for(const [id,text,cls] of buttons){if(!el(id)){const b=document.createElement('button');b.id=id;b.type='button';b.textContent=text;b.className=cls+' hide';row.appendChild(b)}}}
function steps(active){document.querySelectorAll('.upload-steps span').forEach((x,i)=>x.classList.toggle('active',i<active))}
function assess(){const batches=(typeof data!=='undefined'&&data.batches)||[],same=batches.find(b=>b.period_end===report.period_end),latest=[...batches].sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)))[0];if(same)mode='replace';else if(!latest||report.period_end>latest.period_end)mode='latest';else mode='history';const box=el('publishMode');box.classList.remove('hide');if(mode==='replace'){box.className='mode-box notice error';box.innerHTML=`<strong>相同月份：${report.period_end.slice(0,7)}</strong>發布後會取代該月份全部會員資料，其他月份不受影響。`;el('publishBtn').textContent='確認取代月份資料'}else if(mode==='history'){box.className='mode-box notice info';box.innerHTML=`<strong>歷史月份：${report.period_end.slice(0,7)}</strong>發布後只加入歷史紀錄，不會改變最新月份。`;el('publishBtn').textContent='加入歷史紀錄'}else{box.className='mode-box notice ok';box.innerHTML=`<strong>新月份：${report.period_end.slice(0,7)}</strong>發布後會成為最新月份。`;el('publishBtn').textContent='發布為最新月份'}steps(3)}
function reset(){report=null;sourceBase64=null;el('file').value='';el('checkResult').innerHTML='';el('preview')?.classList.add('hide');el('publishMode')?.classList.add('hide');['publishBtn','resetBtn','downloadCsvBtn'].forEach(id=>el(id)?.classList.add('hide'));steps(1)}
function csv(){if(!report)return;const rows=report.members.map(m=>({會員:m.member_name,總分:m.total_score,燈號:lightName(m.light)})),keys=Object.keys(rows[0]||{}),q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',text='\ufeff'+[keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`${report.period_end.slice(0,7)}-upload-audit.csv`;a.click()}
async function readFile(f){ensureUI();steps(2);el('checkResult').innerHTML='<div class="notice info">正在讀取及核對 Excel…</div>';sourceBase64=await file64(f);const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false}),keys=rows.length?Object.keys(rows[0]):[],find=terms=>keys.find(k=>terms.some(t=>String(k).toLowerCase().includes(t))),map={member_name:find(['member','會員','姓名','name']),total_score:find(['total','總分','score']),light:find(['light','燈']),training_score:find(['training','培訓']),absence_score:find(['absence','缺席']),lateness_score:find(['late','遲到']),one_to_one_score:find(['one to one','1-2-1','一對一']),referral_score:find(['referral','引薦']),biz_give_score:find(['biz','生意']),visitor_score:find(['visitor','嘉賓'])},errors=[],warnings=[];if(!rows.length)errors.push('Excel 沒有可讀取資料');if(!map.member_name)errors.push('找不到會員姓名欄');if(!map.total_score)errors.push('找不到總分欄');const period=detectPeriod(f.name);if(!period)errors.push('檔案名稱未能辨認月份，請加入例如 2026-07');const members=rows.filter(r=>String(r[map.member_name]||'').trim()).map(r=>{const m={};for(const[k,v]of Object.entries(map))m[k]=v?r[v]:'';m.member_name=String(m.member_name).trim();['total_score','training_score','absence_score','lateness_score','one_to_one_score','referral_score','biz_give_score','visitor_score'].forEach(k=>m[k]=num(m[k]));m.light=light(m.light,m.total_score);m.previous_score=null;m.raw_metrics=r;m.improvement_tips=typeof makeTips==='function'?makeTips(m):[];m.recap_text=typeof makeRecap==='function'?makeRecap(m):'';return m});const dup=members.map(m=>norm(m.member_name)).filter((x,i,a)=>a.indexOf(x)!==i);if(dup.length)errors.push('Excel 內有重複會員姓名');members.forEach(m=>{const sum=scoreSum(m);if(sum!==m.total_score)warnings.push(`${m.member_name}：分項合計 ${sum}，Excel總分 ${m.total_score}`)});report=period?{period_start:period.start,period_end:period.end,source_filename:f.name,members}:null;el('checkResult').innerHTML=(errors.length?`<div class="notice error">${errors.map(safe).join('<br>')}</div>`:`<div class="notice ok">核對完成：${members.length} 位會員。正式分數會忠實按 Excel 發布。</div>`)+(warnings.length?`<div class="notice">有 ${warnings.length} 項分項合計與總分不同；網站仍以 Excel 總分為準。<br>${warnings.slice(0,20).map(safe).join('<br>')}</div>`:'');const preview=el('preview');if(preview){preview.classList.remove('hide');preview.innerHTML=`<h2>發布前預覽</h2><p><b>檔案：</b>${safe(f.name)}　<b>月份：</b>${period?period.end.slice(0,7):'未能辨認'}　<b>會員：</b>${members.length}</p><div class="table-wrap"><table><thead><tr><th>會員</th><th>總分</th><th>燈號</th></tr></thead><tbody>${members.map(m=>`<tr><td>${safe(m.member_name)}</td><td>${m.total_score}</td><td>${lightName(m.light)}</td></tr>`).join('')}</tbody></table></div>`}el('resetBtn').classList.remove('hide');el('downloadCsvBtn').classList.remove('hide');el('publishBtn').classList.toggle('hide',!!errors.length);if(!errors.length)assess()}
async function publish(){if(!report)return;if(mode==='replace'&&!confirm(`確認取代 ${report.period_end.slice(0,7)} 全部會員資料？`))return;const b=el('publishBtn');b.disabled=true;b.textContent='發布中…';try{const r=await api('publish',{report,source_file_base64:sourceBase64,replace_existing:mode==='replace'});el('checkResult').innerHTML=`<div class="notice ok">發布成功：${r.period_end.slice(0,7)}，共 ${r.member_count} 位會員。</div>`;steps(4);data=await api('history');renderAll();report=null}catch(e){el('checkResult').innerHTML=`<div class="notice error">${safe(e.message)}</div>`}finally{b.disabled=false;b.textContent='確認發布'}}
function install(){ensureUI();const file=el('file');if(!file||file.__uploadV2)return;file.__uploadV2=true;file.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{await readFile(f)}catch(err){el('checkResult').innerHTML=`<div class="notice error">${safe(err.message)}</div>`}};el('publishBtn').onclick=publish;el('resetBtn').onclick=reset;el('downloadCsvBtn').onclick=csv;steps(1)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,300);
})();