(function(){
'use strict';
const el=id=>document.getElementById(id);
let report=null,sourceBase64=null,mode='latest',parseValid=false;
const norm=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase();
const head=s=>norm(s).replace(/[\s_–—:：()（）/\\.]/g,'');
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const light=(v,s)=>{v=String(v).toLowerCase();if(v.includes('綠')||v.includes('green'))return'green';if(v.includes('黃')||v.includes('yellow'))return'yellow';if(v.includes('紅')||v.includes('red'))return'red';if(v.includes('黑')||v.includes('black'))return'black';return s>=70?'green':s>=50?'yellow':s>=30?'red':'black'};
const lightName=l=>({green:'綠燈',yellow:'黃燈',red:'紅燈',black:'黑燈'})[l]||l;
const num=v=>Number(String(v??0).replace(/[$,HKD\s]/gi,''))||0;
function file64(f){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)})}
function monthEnd(y,m){return new Date(Date.UTC(+y,+m,0)).getUTCDate()}
function periodFromMonth(value){if(!/^20\d{2}-\d{2}$/.test(value||''))return null;const[y,m]=value.split('-'),day=String(monthEnd(y,m)).padStart(2,'0');return{start:`${y}-${m}-01`,end:`${y}-${m}-${day}`}}
function detectMonth(filename,rows){let d=filename.match(/(20\d{2})[-_ ]?(\d{1,2})/);if(!d){d=filename.match(/(?:^|\D)(\d{1,2})[-_ ]?(20\d{2})(?:\D|$)/);if(d)d=[d[0],d[2],d[1]]}if(d)return`${d[1]}-${String(d[2]).padStart(2,'0')}`;for(const row of rows.slice(0,20)){for(const value of Object.values(row)){const s=String(value||''),m=s.match(/(20\d{2})[-\/.](\d{1,2})/);if(m)return`${m[1]}-${String(m[2]).padStart(2,'0')}`}}return''}
function scoreSum(m){return['training_score','absence_score','lateness_score','one_to_one_score','referral_score','biz_give_score','visitor_score'].reduce((s,k)=>s+num(m[k]),0)}
function findMember(keys){return keys.find(k=>['會員','member','姓名','name'].includes(head(k)))||keys.find(k=>/(會員|member|姓名|name)/i.test(String(k)))}
function findTotal(keys){return keys.find(k=>{const s=head(k);return!/(重算|recalc|七項合計)/i.test(String(k))&&(s.includes('excel總分')||s==='總分'||s.includes('totalscore')||s==='total')})}
function findLight(keys){return keys.find(k=>/(燈號|trafficlight|light)/i.test(String(k)))}
function findScore(keys,terms){return keys.find(k=>{const raw=String(k),s=head(k);if(/重算|recalc/i.test(raw))return false;const term=terms.some(t=>s.includes(head(t)));const scoreSignal=/excel|得分|score/i.test(raw)||s.endsWith('分');return term&&scoreSignal})}
function makeMap(keys){return{member_name:findMember(keys),total_score:findTotal(keys),light:findLight(keys),training_score:findScore(keys,['培訓','training']),absence_score:findScore(keys,['出席','attendance','absence']),lateness_score:findScore(keys,['準時','punctual','lateness']),one_to_one_score:findScore(keys,['1-2-1','121','一對一','one to one']),referral_score:findScore(keys,['引薦','referral']),biz_give_score:findScore(keys,['生意額','biz give','business']),visitor_score:findScore(keys,['嘉賓','visitor'])}}
function sheetCandidate(wb,name){const sheet=wb.Sheets[name],rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false}),keys=rows.length?Object.keys(rows[0]):[],map=makeMap(keys),scoreKeys=['training_score','absence_score','lateness_score','one_to_one_score','referral_score','biz_give_score','visitor_score'],fitness=(map.member_name?5:0)+(map.total_score?5:0)+scoreKeys.filter(k=>map[k]).length;return{name,rows,keys,map,fitness}}
function chooseSheet(wb){return wb.SheetNames.map(n=>sheetCandidate(wb,n)).sort((a,b)=>b.fitness-a.fitness||b.rows.length-a.rows.length)[0]}
function ensureUI(){const card=el('file')?.closest('.card');if(!card)return;let modeBox=el('publishMode');if(!modeBox){modeBox=document.createElement('div');modeBox.id='publishMode';modeBox.className='mode-box hide';el('checkResult').after(modeBox)}if(!el('monthConfirmV2')){const box=document.createElement('div');box.id='monthConfirmV2';box.className='mode-box hide';box.innerHTML='<label><strong>確認發布月份</strong><input id="reportMonthV2" class="field" type="month"><small class="muted">請核對月份後才發布，避免覆蓋錯誤月份。</small></label>';modeBox.before(box);box.querySelector('input').onchange=e=>setMonth(e.target.value)}let row=card.querySelector('.row');if(!row){row=document.createElement('div');row.className='row';card.appendChild(row)}const buttons=[['publishBtn','確認發布','btn'],['resetBtn','取消上載','btn light'],['downloadCsvBtn','下載核對 CSV','btn light']];for(const[id,text,cls]of buttons){if(!el(id)){const b=document.createElement('button');b.id=id;b.type='button';b.textContent=text;b.className=cls+' hide';row.appendChild(b)}}}
function steps(active){document.querySelectorAll('.upload-steps span').forEach((x,i)=>x.classList.toggle('active',i<active))}
function setMonth(value){const p=periodFromMonth(value);if(!report||!p)return;report.period_start=p.start;report.period_end=p.end;const pm=el('previewMonthV2');if(pm)pm.textContent=value;if(parseValid){el('publishBtn').classList.remove('hide');assess()}}
function assess(){if(!report?.period_end)return;const batches=(typeof data!=='undefined'&&data.batches)||[],same=batches.find(b=>b.period_end===report.period_end),latest=[...batches].sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)))[0];if(same)mode='replace';else if(!latest||report.period_end>latest.period_end)mode='latest';else mode='history';const box=el('publishMode');box.classList.remove('hide');if(mode==='replace'){box.className='mode-box notice error';box.innerHTML=`<strong>相同月份：${report.period_end.slice(0,7)}</strong>發布後會取代該月份全部會員資料，其他月份不受影響。`;el('publishBtn').textContent='確認取代月份資料'}else if(mode==='history'){box.className='mode-box notice info';box.innerHTML=`<strong>歷史月份：${report.period_end.slice(0,7)}</strong>發布後只加入歷史紀錄，不會改變最新月份。`;el('publishBtn').textContent='加入歷史紀錄'}else{box.className='mode-box notice ok';box.innerHTML=`<strong>新月份：${report.period_end.slice(0,7)}</strong>發布後會成為最新月份。`;el('publishBtn').textContent='發布為最新月份'}steps(3)}
function reset(){report=null;sourceBase64=null;parseValid=false;el('file').value='';el('checkResult').innerHTML='';el('preview')?.classList.add('hide');el('publishMode')?.classList.add('hide');el('monthConfirmV2')?.classList.add('hide');['publishBtn','resetBtn','downloadCsvBtn'].forEach(id=>el(id)?.classList.add('hide'));steps(1)}
function csv(){if(!report)return;const rows=report.members.map(m=>({會員:m.member_name,培訓:m.training_score,出席:m.absence_score,準時:m.lateness_score,'1-2-1':m.one_to_one_score,引薦:m.referral_score,生意額:m.biz_give_score,嘉賓:m.visitor_score,總分:m.total_score,燈號:lightName(m.light)})),keys=Object.keys(rows[0]||{}),q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',text='\ufeff'+[keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`${report.period_end?.slice(0,7)||'report'}-upload-audit.csv`;a.click()}
async function readFile(f){
  ensureUI();steps(2);el('checkResult').innerHTML='<div class="notice info">正在讀取及核對 Excel…</div>';sourceBase64=await file64(f);
  const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),chosen=chooseSheet(wb),rows=chosen?.rows||[],keys=chosen?.keys||[],map=chosen?.map||{},errors=[],warnings=[],required={member_name:'會員姓名',total_score:'Excel總分',training_score:'Excel培訓分',absence_score:'Excel出席分',lateness_score:'Excel準時分',one_to_one_score:'Excel 1-2-1分',referral_score:'Excel引薦分',biz_give_score:'Excel生意額分',visitor_score:'Excel嘉賓分'};
  if(!rows.length)errors.push('Excel 沒有可讀取資料');for(const[k,label]of Object.entries(required))if(!map[k])errors.push(`找不到「${label}」欄，請確認上載原始 Traffic Excel`);
  const members=rows.filter(r=>String(r[map.member_name]||'').trim()).map(r=>{const m={};for(const[k,v]of Object.entries(map))m[k]=v?r[v]:'';m.member_name=String(m.member_name).trim();['total_score','training_score','absence_score','lateness_score','one_to_one_score','referral_score','biz_give_score','visitor_score'].forEach(k=>m[k]=num(m[k]));m.light=light(m.light,m.total_score);m.previous_score=null;m.raw_metrics=r;m.improvement_tips=typeof makeTips==='function'?makeTips(m):[];m.recap_text=typeof makeRecap==='function'?makeRecap(m):'';return m});
  const dup=members.map(m=>norm(m.member_name)).filter((x,i,a)=>a.indexOf(x)!==i);if(dup.length)errors.push('Excel 內有重複會員姓名');members.forEach(m=>{const sum=scoreSum(m);if(sum!==m.total_score)warnings.push(`${m.member_name}：七項合計 ${sum}，Excel總分 ${m.total_score}`)});
  const month=detectMonth(f.name,rows),p=periodFromMonth(month);report={period_start:p?.start||'',period_end:p?.end||'',source_filename:f.name,members};parseValid=!errors.length;
  el('checkResult').innerHTML=(errors.length?`<div class="notice error">${errors.map(safe).join('<br>')}</div>`:`<div class="notice ok">核對完成：已從「${safe(chosen?.name||'')}」讀取 ${members.length} 位會員，七項正式分數均鎖定 Excel 分數欄。</div>`)+(warnings.length?`<div class="notice">有 ${warnings.length} 項七項合計與總分不同；網站仍以 Excel總分為準。<br>${warnings.slice(0,20).map(safe).join('<br>')}</div>`:'');
  const preview=el('preview');if(preview){preview.classList.remove('hide');preview.innerHTML=`<h2>發布前預覽</h2><p><b>檔案：</b>${safe(f.name)}　<b>工作表：</b>${safe(chosen?.name||'')}　<b>月份：</b><span id="previewMonthV2">${month||'請選擇'}</span>　<b>會員：</b>${members.length}</p><div class="table-wrap"><table><thead><tr><th>會員</th><th>培訓</th><th>出席</th><th>準時</th><th>1-2-1</th><th>引薦</th><th>生意額</th><th>嘉賓</th><th>總分</th><th>燈號</th></tr></thead><tbody>${members.map(m=>`<tr><td>${safe(m.member_name)}</td><td>${m.training_score}</td><td>${m.absence_score}</td><td>${m.lateness_score}</td><td>${m.one_to_one_score}</td><td>${m.referral_score}</td><td>${m.biz_give_score}</td><td>${m.visitor_score}</td><td><b>${m.total_score}</b></td><td>${lightName(m.light)}</td></tr>`).join('')}</tbody></table></div>`}
  el('monthConfirmV2').classList.remove('hide');el('reportMonthV2').value=month;el('resetBtn').classList.remove('hide');el('downloadCsvBtn').classList.toggle('hide',!members.length);el('publishBtn').classList.add('hide');el('publishMode').classList.add('hide');if(parseValid&&month)setMonth(month);else if(parseValid)el('checkResult').insertAdjacentHTML('beforeend','<div class="notice info">請先選擇正確月份，再進行發布。</div>');
}
async function publish(){if(!report||!parseValid||!report.period_end)return;if(mode==='replace'&&!confirm(`確認取代 ${report.period_end.slice(0,7)} 全部會員資料？`))return;const b=el('publishBtn');b.disabled=true;b.textContent='發布中…';try{const r=await api('publish',{report,source_file_base64:sourceBase64,replace_existing:mode==='replace'});el('checkResult').innerHTML=`<div class="notice ok">發布成功：${r.period_end.slice(0,7)}，共 ${r.member_count} 位會員。</div>`;steps(4);data=await api('history');renderAll();report=null}catch(e){el('checkResult').innerHTML=`<div class="notice error">${safe(e.message)}</div>`}finally{b.disabled=false;b.textContent='確認發布'}}
function install(){ensureUI();const file=el('file');if(!file||file.__uploadV2)return;file.__uploadV2=true;file.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{await readFile(f)}catch(err){el('checkResult').innerHTML=`<div class="notice error">${safe(err.message)}</div>`}};el('publishBtn').onclick=publish;el('resetBtn').onclick=reset;el('downloadCsvBtn').onclick=csv;steps(1)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,300);
})();